### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by tomkersten** [tietgenlabs/anvil-proxy-npm#11]
Would be nice to have some events on installations & published packages in our metrics system.

Some hooks for installation and `/publish` would be great (not sure of URL for installation) which could be used to inject custom code would be nice...something that passes in the parsed data (say, the package name, version, and the user's UUID at least)

**Comment by psexton** [comment]
The client will also be logging this.

**Comment by tomkersten** [comment]
K. Will close.
