### ISSUE TITLE
Implement Anvil Access Token verification & request transformation

### ISSUE THREAD

**Issue by tomkersten** [tietgenlabs/anvil-proxy-npm#5]
All requests must have at least the scope specified as the "read support" scope of the application. Any request with a token which does not should return a `401 Not Authorized` response code and not forward the request into the proxy application.

When a request is received with an Access token with the "read" scope present (and the request is _not_ to `publish` a package), the `Authorization: Bearer [token]` header should be removed and replaced with a Basic Auth header  (`Authorization: Basic Base64(UUID:HARDCODED_PASSWORD)`), and the request is forwarded on to the URI specified in the proxy configuration.

The response from the URI endpoint should be directly returned to the client without modification.

**Comment by tomkersten** [comment]
completed, @psexton ?

**Comment by psexton** [comment]
:+1:
