### ISSUE TITLE
Implement publish endpoint

### ISSUE THREAD

**Issue by tomkersten** [tietgenlabs/anvil-proxy-npm#6]
Overview
=======

The `publish` endpoint (`/publish`) will be handled differently. The short version is that this endpoint will "shell out" to `npm` in order to publish a package. The reason for this is endpoints is twofold:

1. `npm publish` makes several requests in the background, some of which do not require authentication, which we don't want to do "on the client" (read: "desktop") application.
2. Adding this removes the need an NPM(/NodeJS) to be installed on the clients, dramatically reducing the complexity of demploying this to "non-NodeJS" developers.

How will it behave?
===============

1. The `/publish` endpoint will require an Access Token with the list of scopes configured for "write" access to the application. If this is not present, the endpoint should return a `401 Not Authorized` response code and not proxy the request through to the specified application URI.
1. The body of the request will contain a `.tar.gz` file and the `Content-Type` header will be `applicaton/octet-stream`. This attachment will be saved as a temporary file on the server.
1. The server is then responsible for executing the `npm publish` command, passing in the UUID associated with the Access Token, the hard-coded password from the `adduser` flow, and the temporary file stored in the previous step.
1. The temporary file must be deleted.
1. The response from the proxied application will be returned to the client unmodified.

**Comment by tomkersten** [comment]
Completed now, @psexton ?

**Comment by psexton** [comment]
:shipit:
