### ISSUE TITLE
Handling refresh tokens

### ISSUE THREAD

**Issue by tomkersten** [tietgenlabs/anvil-proxy-npm#7]
How should we handle the refresh tokens?

I see two options:

1. **We could register the Desktop client as the client in Anvil.** The upside of this is that the client would get the refresh token and be able to deal with token expirations itself, keeping the server/proxy simpler. The downside is that the flow for authorizing and getting the token may be painful for the user ("open a browser...copy something here", etc).
1. **We could register the proxy as a client and make _it_ responsible for handling the refresh tokens.** This makes it easier for the client, and with an "internal" client application, we shouldn't need to worry about the user authorizing access. However, if we go down this route we either need to give the client the refresh token to pass back up to us on every request (so we don't need to manage it), or we need to manage it somewhere on the server when an expired token is received.

@christiansmith Any thoughts on this?

**Comment by tomkersten** [comment]
We are using "long-lasting" tokens and wil modify to have client-side refresh when the OAuth2 spec for native is more stable, correct @christiansmith ?

**Comment by christiansmith** [comment]
We can definitely look to improve this for the long term. After diving in, I'm not sure I entirely understand the purpose of the drafted OIDC native spec. It may be possible to do what we need within the constraints of existing finalized specs. Requires additional research.

**Comment by tomkersten** [comment]
Agreed. Closing for now.
