### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by tomkersten** [tietgenlabs/anvil-proxy-npm#9]
We need to clean up & standardize logging. I'm getting verklempt...

Discuss.

**Comment by tomkersten** [comment]
Some requirements:

1. Remove log statement on startup and/or convert it to JSON object to prevent couch from complaining if being run via the `couchapp` feature of CouchDB.
1. Logging should be able to be configured to take place in different directory than the application/proxy root directory in order to support shared/mounted volumes. Only mentioning this in case bunyan does not create missing "parent" directories. If that is the case, I suggest creating a `log` directory in the application root with a `.gitkeep` file in it. Local development could write to this directory if desired and shared network mounts could be mounted at the `log` mountpoint when deployed.

**Comment by psexton** [comment]
Requirement 1 implemented in 4e8f34daaf743a96f92fd292f5bef0a603729352

**Comment by christiansmith** [comment]
2 looks to be implemented as well in `config.logger.streams.path` unless I'm missing something?

```
// config.json
  "logger": {
    "name": "proxy",
    "streams": [{
      "path": "anvil-proxy-npm.log"
    }]
  }
```

**Comment by tomkersten** [comment]
@christiansmith agreed. mostly was referring to the actual deployment setup...my apologies...not applicable to the overall project.

**Comment by tomkersten** [comment]
Seems answered. Closing.
